const projects = [
  {
    id: 1,
    image: "./assets/artsy.png",
    name: "Artsy",
    github: "https://github.com/omotayobolu/artsy",
    live: "https://artsyphotography.vercel.app/",
    tools: ["React JS", "Tailwind CSS", "ExpressJS", "MongoDB"],
  },
  {
    id: 2,
    image: "./assets/timbu.png",
    name: "Timbu store",
    github: "https://github.com/omotayobolu/timbu-store",
    live: "https://timbu-stores.vercel.app/",
    tools: ["NextJS", "TypeScript", "Tailwind CSS"],
  },
  {
    id: 3,
    image: "./assets/getlinked.png",
    name: "GetLinked Hackathon",
    github: "https://github.com/omotayobolu/getlinked",
    live: "https://getlinked-taupe-seven.vercel.app/",
    tools: ["Next JS", "Tailwind CSS"],
  },
  // {
  //   id: 4,
  //   image: "./assets/bookmark.png",
  //   name: "Bookmark landing page",
  //   github: "https://github.com/omotayobolu/bookmark-landing-page",
  //   live: "https://omotayobolu.github.io/bookmark-landing-page/",
  //   tools: ["HTML", "CSS", "Javascript"],
  // },
  {
    id: 5,
    image: "./assets/countries.png",
    name: "Countries App",
    github: "https://github.com/omotayobolu/Countries",
    live: "https://countries-app-omotayo.netlify.app/",
    tools: ["React JS", "SASS"],
  },
  // {
  //   id: 5,
  //   image: "./assets/crappo.png",
  //   name: "Crappo Cryptocurrency Landing Page",
  //   github: "https://github.com/omotayobolu/crappo-cryptocurrency",
  //   live: "https://crappo-cryptocurrencyy.netlify.app/",
  //   tools: ["React JS", "SASS"],
  // },

  // {
  //   id: 6,
  //   image: "./assets/image-gallery.png",
  //   name: "Image Gallery",
  //   github: "https://github.com/omotayobolu/image-gallery",
  //   live: "https://image-gallery-hngx3.netlify.app/",
  //   tools: ["React JS", "Tailwind CSS", "Firebase"],
  // },
  // {
  //   id: 7,
  //   image: "./assets/quizzical.png",
  //   name: "Quizzical App",
  //   github: "https://github.com/omotayobolu/Quizzical-App/",
  //   live: "https://quizzical-app-omotayo.netlify.app/",
  //   tools: ["React JS", "CSS"],
  // },
  // {
  //   id: 8,
  //   image: "./assets/todo.png",
  //   name: "ToDo App",
  //   github: "https://github.com/omotayobolu/todo-app/",
  //   live: "https://todo-app-omotayo.netlify.app/",
  //   tools: ["React JS", "CSS"],
  // },
];

export default projects;
